name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake g++

    - name: Remove CMakeCache.txt
      run: rm -f build/CMakeCache.txt

    - name: Configure CMake
      run: cmake -S . -B build -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      working-directory: build
      run: ctest -C Release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyExecutable
        path: build/MyExecutable
